name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: |
          cd apps/api
          npx prisma generate

      - name: Build Apps
        run: npm run build

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: './apps/web/.next, ./apps/web/*, ./apps/web/.*, ./apps/api, ./package*.json, ./turbo.json, ./.husky'
          target: '~/mini-insta'
